### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by aniketmodi-work** [krlvm/AccentColorizer-E11#22]
How do I reverse the affects of this?

**Comment by krlvm** [comment]
Killing the process is enough

**Comment by Valer100** [comment]
Looks like if you overlay `#251840` with around 32% (82 / 255 * 100) opacity over `#0078D4` you can get `#0C59A4`. From my tests, when I overlay `#251840` with the same opacity percent over other colors I get similar darker colors.

**Comment by krlvm** [comment]
> what we should do about the Spotlight-related glyphs using a slightly darker blue color

Yeah, that's one of the tricky parts. There's also might be a case when user's non-standard accent color is already used by one of the stock glyphs, so reverting will not end well (although this would result in bad results after changing the accent color too).

I think we should've been backing up the assets (e.g. by copying them to kind of `.bak` files) and recolorize the original versions each time. It would also solve all problems with the `-Revert` option as we will only need to replace the active files with the original ones and restore the proper access rights.

**Comment by Valer100** [comment]
> There's also might be a case when user's non-standard accent color is already used by one of the stock glyphs, so reverting will not end well (although this would result in bad results after changing the accent color too).

From what I've seen, the other colors used by most of the glyphs are `#E0DFDF`, `#FAFAFA` and `#000000` (used as `black` in the files) for light mode glyphs and `#555555` (used as `#555`), `#202020` and `#FFFFFF` (used as `white`) for dark mode glyphs. The only colors that the program will never be able to replace are black, white and #555. To set the other colors as accent colors, you'll have to modify the `AccentPalette` registry value accordingly from `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Accent` (this means that you know what you're doing and that the custom colors you set might cause contrast issues), because Windows won't allow you to set these colors as accent colors because of contrast issues (will show a "This color is not supported" yellow/red text)

<img alt="Image" src="https://github.com/user-attachments/assets/cdec59d4-19f1-446d-8a9f-c486a6c58c69" />
<br><br>

> I think we should've been backing up the assets (e.g. by copying them to kind of .bak files) and recolorize the original versions each time. It would also solve all problems with the -Revert option as we will only need to replace the active files with the original ones and restore the proper access rights.

The backup idea seems also great, but also tricky at the same time. What would happen (after the backup was already made) when some glyphs get modified after a Windows update, new glyphs get added or the glyphs path changes again on newer Windows versions?

> Looks like if you overlay #251840 with around 32% (82 / 255 * 100) opacity over #0078D4 you can get #0C59A4. From my tests, when I overlay #251840 with the same opacity percent over other colors I get similar darker colors.

Also, what do you think about this? (my previous comment)

**Comment by krlvm** [comment]
> The backup idea seems also great, but also tricky at the same time. What would happen (after the backup was already made) when some glyphs get modified after a Windows update, new glyphs get added or the glyphs path changes again on newer Windows versions?

If glyphs paths change, ACE11 will break anyway

To deal with recently added glyphs, at each ACE11 startup we can backup all glyphs for which there is no backup, i.e. for all glyphs for which there is no `filename.svg.bak` in the same directory

> new glyphs get added or the glyphs path changes again on newer Windows versions

This is more tricky indeed, did not think about that. We could compare the current file content length against the backed up file content length, given that color codes length are always the same. But there may be rare cases when the content has changed substantially, but the length by coincidence remains the same.

> Also, what do you think about this? (my previous comment)

Seems valid, but if this algorithm ever changes, it will no longer work, otherwise it's great

**Comment by Valer100** [comment]
> > Also, what do you think about this? (my previous comment)
>
> Seems valid, but if this algorithm ever changes, it will no longer work, otherwise it's great

Thanks! I don't think it will change, since the 23H2 and newer versions of the light mode Spotlight glyphs use the correct accent color. Anyway, I'll open a PR that includes the `-Revert` argument and the proper colorization of the 22H2 light mode Spotlight glyphs later today or tomorrow.
